# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97c171b6f1e0d8eb7ed9a6fcc109fac7c231be8d95d895b801c81b368b7db209d1a6bfdc879f8e582ecd121698dd04a365b93b55e617390a8fa0531155482d06

test:
  secret_key_base: 6367c5d0103d70c910a7a95bc23b619fdff18d4c125e9adfb2b1597ad0d9d8b32ff18a525a42f07647e106d29a4b1cea8c721dd3682327b0cc892c82581eb3d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
